Repository Mo-yoy/Moyoy-Backend, pull requests merged in 2025-08, with the labels that each got.

#100 Setting: add Sonar Cloud
  .github/workflows/sonarcloud.yml
  build.gradle
Labels: ⚙ Setting, size/M, :shipit: 승률

#101 Refactor: restructure into multi-module
  Moyoy-Api/src/main/java/com/moyoy/api/presentation/v1/domain/pr_review/PrReviewController.java
  Moyoy-Api/src/main/java/com/moyoy/api/presentation/v1/domain/pr_review/request/PrReviewFormRequest.java
  Moyoy-Api/src/main/java/com/moyoy/api/presentation/v1/domain/pr_review/request/PrReviewListRequest.java
  Moyoy-Api/src/main/java/com/moyoy/api/presentation/v1/domain/pr_review/response/PrReviewDetailResponse.java
  Moyoy-Api/src/main/java/com/moyoy/api/presentation/v1/domain/pr_review/response/PrReviewListResponse.java
  Moyoy-Api/src/main/java/com/moyoy/api/presentation/v1/domain/pr_review/response/PrReviewRedirectResponse.java
  Moyoy-Api/src/main/java/com/moyoy/api/presentation/v1/domain/pr_review/response/PrReviewUpdateFormResponse.java
  Moyoy-Common/src/main/java/com/moyoy/common/exception/pr_review/PrReviewErrorCode.java
  Moyoy-Core/src/main/java/com/moyoy/core/db_access/domain/pr_review/PrReviewHitsJpaRepository.java
  Moyoy-Core/src/main/java/com/moyoy/core/db_access/domain/pr_review/PrReviewHitsRepository.java
  Moyoy-Core/src/main/java/com/moyoy/core/db_access/domain/pr_review/PrReviewHitsRepositoryImpl.java
  Moyoy-Core/src/main/java/com/moyoy/core/db_access/domain/pr_review/PrReviewJpaRepository.java
  Moyoy-Core/src/main/java/com/moyoy/core/db_access/domain/pr_review/PrReviewRepository.java
  Moyoy-Core/src/main/java/com/moyoy/core/db_access/domain/pr_review/PrReviewRepositoryImpl.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/business/PrReviewService.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/business/dto/PrReviewContent.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/business/dto/PrReviewCreateResult.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/business/dto/PrReviewDetailResult.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/business/dto/PrReviewListResult.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/business/dto/PrReviewSearchCriteria.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/business/dto/PrReviewUpdateResult.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/Position.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/PrReview.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/PrReviewHits.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/PrReviewHitsReader.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/PrReviewReader.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/PrReviewUpdater.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/dto/PrReviewContentData.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/dto/PrReviewCreateData.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/dto/PrReviewDetail.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/dto/PrReviewListData.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/dto/PrReviewSummary.java
  Moyoy-Core/src/main/java/com/moyoy/core/domain/pr_review/implement/dto/SearchCriteria.java
Labels: :trollface: 재영, 🔨 Refactor, size/XL

#107 Setting: Ignore SonarCloud Quality Gate result in CI
  .github/workflows/sonarcloud.yml
Labels: ⚙ Setting, :shipit: 승률, size/XS

#119 Refactor: improve cache handling logic
  Moyoy-Infra/src/main/java/com/moyoy/infra/database/redis/follow/GithubFollowSnapshotCacheManager.java
  Moyoy-Infra/src/main/java/com/moyoy/infra/database/redis/support/config/CacheConfig.java
  Moyoy-Infra/src/main/java/com/moyoy/infra/database/redis/support/config/CustomCacheErrorHandler.java
  Moyoy-Infra/src/main/java/com/moyoy/infra/database/redis/support/config/RedisConfig.java
Labels: size/S, :shipit: 승률, 🔨 Refactor
