Repository Mo-yoy/Moyoy-Backend, pull requests merged in 2025-05, with the labels that each got.

#53 Feat: PR 리뷰 요청 기능 추가
  src/main/java/com/moyo/backend/common/exception/CommonErrorCode.java
  src/main/java/com/moyo/backend/common/model/ApiResponse.java
  src/main/java/com/moyo/backend/pr_review/application/PrReviewService.java
  src/main/java/com/moyo/backend/pr_review/application/port/PrReviewHitsRepository.java
  src/main/java/com/moyo/backend/pr_review/application/port/PrReviewRepository.java
  src/main/java/com/moyo/backend/pr_review/domain/PrReview.java
  src/main/java/com/moyo/backend/pr_review/domain/PrReviewHits.java
  src/main/java/com/moyo/backend/pr_review/domain/position/Position.java
  src/main/java/com/moyo/backend/pr_review/dto/PrReviewDto.java
  src/main/java/com/moyo/backend/pr_review/dto/request/PrReviewCreateRequestDto.java
  src/main/java/com/moyo/backend/pr_review/dto/request/PrReviewListRequestDto.java
  src/main/java/com/moyo/backend/pr_review/dto/request/PrReviewUpdateRequestDto.java
  src/main/java/com/moyo/backend/pr_review/dto/response/PrReviewCreateResponseDto.java
  src/main/java/com/moyo/backend/pr_review/dto/response/PrReviewDetailResponseDto.java
  src/main/java/com/moyo/backend/pr_review/dto/response/PrReviewListResponseDto.java
  src/main/java/com/moyo/backend/pr_review/dto/response/PrReviewUpdateFormResponseDto.java
  src/main/java/com/moyo/backend/pr_review/dto/response/PrReviewUpdateResponseDto.java
  src/main/java/com/moyo/backend/pr_review/infrastructure/PrReviewHitsJpaRepository.java
  src/main/java/com/moyo/backend/pr_review/infrastructure/PrReviewHitsRepositoryImpl.java
  src/main/java/com/moyo/backend/pr_review/infrastructure/PrReviewJpaRepository.java
  src/main/java/com/moyo/backend/pr_review/infrastructure/PrReviewRepositoryImpl.java
  src/main/java/com/moyo/backend/pr_review/presentation/PrReviewController.java
Labels: :trollface: 재영, ✨ Feature, size/XL

#51 Refactor: 로그인 리팩토링
  build.gradle
  src/main/java/com/moyo/backend/MoyoBackendApplication.java
  src/main/java/com/moyo/backend/common/constant/MoyoConstants.java
  src/main/java/com/moyo/backend/common/controller/AuthTestController.java
  src/main/java/com/moyo/backend/common/dto/ApiResponse.java
  src/main/java/com/moyo/backend/common/exception/GlobalExceptionHandler.java
  src/main/java/com/moyo/backend/common/util/CookieFactory.java
  src/main/java/com/moyo/backend/common/util/CookieUtils.java
  src/main/java/com/moyo/backend/githubfollow/controller/GithubFollowController.java
  src/main/java/com/moyo/backend/security/config/SecurityConfig.java
  src/main/java/com/moyo/backend/security/jwt/config/JwtConfig.java
  src/main/java/com/moyo/backend/security/jwt/controller/JwtReissueController.java
  src/main/java/com/moyo/backend/security/jwt/domain/JwtRefreshToken.java
  src/main/java/com/moyo/backend/security/jwt/dto/JwtReissueResponse.java
  src/main/java/com/moyo/backend/security/jwt/exception/AuthErrorCode.java
  src/main/java/com/moyo/backend/security/jwt/exception/JwtTokenBlockedException.java
  src/main/java/com/moyo/backend/security/jwt/exception/JwtTokenExpiredException.java
  src/main/java/com/moyo/backend/security/jwt/exception/JwtTokenInvalidException.java
  src/main/java/com/moyo/backend/security/jwt/exception/JwtTokenNotExistException.java
  src/main/java/com/moyo/backend/security/jwt/exception/JwtTokenTypeMismatchException.java
  src/main/java/com/moyo/backend/security/jwt/exception/LoginErrorCode.java
  src/main/java/com/moyo/backend/security/jwt/filter/JWTAuthenticationExceptionHandleFilter.java
  src/main/java/com/moyo/backend/security/jwt/filter/JWTAuthenticationFilter.java
  src/main/java/com/moyo/backend/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/moyo/backend/security/jwt/filter/JwtExceptionHandleFilter.java
  src/main/java/com/moyo/backend/security/jwt/repository/JwtRefreshTokenJpaRepositoryImpl.java
  src/main/java/com/moyo/backend/security/jwt/repository/JwtRefreshTokenRepository.java
  src/main/java/com/moyo/backend/security/jwt/repository/JwtRefreshTokenRepositoryImpl.java
  src/main/java/com/moyo/backend/security/jwt/service/JwtReissueService.java
  src/main/java/com/moyo/backend/security/jwt/util/JwtPayloadReader.java
  src/main/java/com/moyo/backend/security/jwt/util/JwtProvider.java
  src/main/java/com/moyo/backend/security/jwt/util/JwtValidator.java
  src/main/java/com/moyo/backend/security/oauth/CustomAccessDeniedHandler.java
  src/main/java/com/moyo/backend/security/oauth/CustomAuthenticationEntryPoint.java
  src/main/java/com/moyo/backend/security/oauth/CustomOAuth2UserService.java
  src/main/java/com/moyo/backend/security/oauth/GithubOAuth2User.java
  src/main/java/com/moyo/backend/security/oauth/GithubOAuth2UserConverter.java
  src/main/java/com/moyo/backend/security/oauth/HttpCookieOAuth2AuthorizationRequestRepository.java
  src/main/java/com/moyo/backend/security/oauth/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/moyo/backend/security/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/moyo/backend/security/oauth/RdbOAuth2AuthorizedClientService.java
  src/main/java/com/moyo/backend/security/oauth/dto/GithubOAuth2User.java
  src/main/java/com/moyo/backend/security/oauth/dto/GithubUserProfile.java
  src/main/java/com/moyo/backend/security/oauth/dto/UserDto.java
  src/main/java/com/moyo/backend/security/oauth/handler/OAuthLoginSuccessHandler.java
  src/main/java/com/moyo/backend/security/oauth/repository/LoginRepository.java
  src/main/java/com/moyo/backend/security/oauth/repository/LoginRepositoryImpl.java
  src/main/java/com/moyo/backend/security/oauth/service/GithubOAuth2UserService.java
  src/main/java/com/moyo/backend/user/Role.java
  src/main/java/com/moyo/backend/user/User.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
Labels: :shipit: 승률, 🔨 Refactor, size/XXL

#54 Fix: 로그인 리팩토링 후 클래스명, 패키지 위치 변경으로 인한 컴파일 에러 수정
  src/main/java/com/moyo/backend/common/dto/ApiResponse.java
  src/main/java/com/moyo/backend/pr_review/presentation/PrReviewController.java
  src/main/java/com/moyo/backend/security/config/SecurityConfig.java
Labels: 🐞 BugFix, size/M, :shipit: 승률

#57 Fix: Swagger UI 관련 CORS 설정
  src/main/java/com/moyo/backend/common/config/MvcCorsConfig.java
Labels: 🐞 BugFix, :shipit: 승률, size/XS
